spring:
  datasource:

    url: jdbc:mysql://localhost:3306/animes
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.highlight_sql: true
      hibernate.generate_statistics: true
      hibernate:
        hbm2ddl:
            auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: searchengineforanime@gmail.com
    password: gudf jhbz ogpv onxd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
